- name: create docker directories
  file:
    path: "{{ storage_location }}/{{item}}"
    state: directory
    mode: 0755
    owner: '1000'
    group: '1000'
  with_items:
    - docker
    - docker_data