version: '2.2'
services:
  vue:
    image: "{{vue_image}}"
    command: bash -c "apt -qq update && apt -qq -y install bzip2 && yarn install && yarn start"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    network_mode: "host"
    volumes:
      - "{{workspace_location}}/vue-elasticsearch/example:/code"
  dejavu:
    image: "{{dejavu_image}}"
    ports:
      - "1358:1358"
    network_mode: "host"
  kibana:
    image: "{{kibana_image}}"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_URL=http://elasticsearch:9300
    env_file:
      - ./kibana.env
    ports:
      # - "${KIBANA_PORT}:5601"
      - "5601:5601"
    network_mode: "host"
  es01:
    image: "{{elastic_image}}"
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
    env_file:
      - ./es.env
      - ./es-cluster.env
      - ./es-cors.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "{{storage_location}}/data01:/usr/share/elasticsearch/data"
      - "{{backup_location}}/repo2:/backup"
    network_mode: "host"
  es02:
    image: "{{elastic_image}}"
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
    env_file:
      - ./es.env
      - ./es-cluster.env
      - ./es-cors.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "{{storage_location}}/data02:/usr/share/elasticsearch/data"
      - "{{backup_location}}/repo2:/backup"
    network_mode: "host"
  es03:
    image: "{{elastic_image}}"
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
    env_file:
      - ./es.env
      - ./es-cluster.env
      - ./es-cors.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "{{storage_location}}/data03:/usr/share/elasticsearch/data"
      - "{{backup_location}}/repo2:/backup"
    network_mode: "host"
  mf:
    image: "{{crawler_image}}"
    network_mode: "host"
    ports:
      - "8345:8345"
    volumes:
      # - "./mcf-elasticsearch-connector-webCrawler.jar:/usr/share/manifoldcf/connector-lib/mcf-elasticsearch-connector-webCrawler.jar"
      - "./connectors.xml:/usr/share/manifoldcf/connectors.xml"
      - "./properties.xml:/usr/share/manifoldcf/example/properties.xml"
      - "./start-options.env.unix:/usr/share/manifoldcf/example/start-options.env.unix"
  phppgadmin:
    image: "{{phppgadmin_image}}"
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=ManifoldCF
      - PHP_PG_ADMIN_SERVER_HOST=db
      - PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY=false
      - PGADMIN_DEFAULT_EMAIL=postgres
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
    network_mode: "bridge"
    ports:
        - "{{ phppgadmin_port }}:80"
  db:
    image: "{{postgres_image}}"
    ports:
      - "5432:5432"
    network_mode: "host"
    env_file:
      - ./db.env
    volumes:
      - "./my-postgres.conf:/etc/postgresql/postgresql.conf"
      - "{{storage_location}}/db:/var/lib/postgresql/data/pgdata"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local