- hosts: crawler es
  user: "{{ server_user }}"
  become: yes
  roles:
    # es
    - role: virtual-memory
      tags:
        - memory
    - role: es-files-directories
      tags:
        - directories
    # crawler
    - role: db-files-directories
      tags:
        - directories
- import_playbook: localhost.yml