- hosts: crawler es
  user: super_user
  become: yes
  vars_files:
    - [ "group_vars/all/{{ ansible_facts['distribution'] }}.yml" ]

  roles:
    - role: packages
    - role: packages_os
      when: ansible_facts['distribution'] != 'Fedora'

    - role: pip

    - role: docker_repo_rpm
      when: ansible_facts['os_family'] == 'RedHat'
    - role: docker_repo_deb
      when: ansible_facts['os_family'] == 'Debian'
    - role: docker
    - role: docker-files-directories
      tags:
        - directories
    - role: docker-login
      tags:
        - deploy-changes

    # containers prerequests

    # es
    - role: virtual-memory
      tags:
        - memory
    - role: es-files-directories
      tags:
        - directories

    # crawler
    - role: db-files-directories
      tags:
        - directories

    # containers content

    - role: compose
      tags: 
        - deploy-changes


