env: tst
type: crawler

crawler_image: elcom/manifoldcf
crawler_memory: 512m
phppgadmin_image: dockage/phppgadmin
postgres_image: index.docker.io/postgres:{{ postgres_version }}
psql_pass: "{{vault_psql_pass}}"

all_images:
  - "{{crawler_image}}"
  - "{{phppgadmin_image}}"
  - "{{postgres_image}}"