env: tst
type: localhost

# apache_image: php:7.3.16-apache-stretch
# apache_port: 81
# nginx_image: nginx
# nginx_port: 82
vue_image: ebiven/vue-cli

all_images:
  - "{{vue_image}}"
  # - "{{nginx_image}}"
  # - "{{apache_image}}"