- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker repository on deb packaging systems like debian ubuntu
  apt_repository:
    update_cache: yes
    repo: "deb [trusted=yes] http://download.docker.com/linux/{{ os }} {{ os_release }} stable"
    codename: "{{ os_release }}"
    state: present