- name: Install Docker CE
  package:
    name: docker-ce
    state: present
  with_items: 
    - "{{ os }}-docker"

- name: create docker directory
  file:
    path: "/etc/docker"
    state: directory
    mode: 0755
    owner: root
    group: root
  
- name: docker daemon.json
  template: 
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"

- name: add server user to docker gropu
  user:
    name: '{{ server_user }}'
    groups: 
      - docker
    append: yes

- name: Start docker
  service:
    enabled: yes
    name: docker
    state: restarted

- name: Install pip packages
  pip:
    name: "{{ pip_packages }}"
    extra_args: --ignore-installed PyYAML

- name: create data docker directory
  file:
    path: "{{storage_location}}/docker"
    state: directory
    mode: 0755
    owner: root
    group: root