- name: Add Docker repository on rpm packaging systems like centos fedora rhel
  yum_repository:
    name: docker_ce_repo_on_rpm
    description: Docker CE repo
    baseurl: "https://download.docker.com/linux/{{ os }}/{{ os_version }}/{{ ansible_machine }}/stable/"
    gpgcheck: false